import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AmazonPay from 'amazon-pay-react';
import FacebookLogin from 'react-facebook-login';

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}><FacebookLogin
    appId="1088597931155576"
    autoLoad={true}
    fields="name,email,picture"
    onClick={componentClicked}
    callback={responseFacebook} />
      <AmazonPay
        clientId='your-cliendId'
        sellerId='your-sellerId'
        agreementType={'BillingAgreement'}
        scope='profile payments:widget'
        btnType='PwA'
        btnColor='Gold'
        btnSize='medium'
        onConsentChange=''
        handleBillingAgreementId=''
        billingAgreementId=''
        useAmazonAddressBook={true}
/>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
